config/routes.rb
Rails.application.routes.draw do
  root to: 'fills#index'
  resources :fills
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  has_many :fills

  def ppm_to_s
    "#{sprintf('%.1f', ppm)} lifetime pence per mile"
  end

  def mpg_to_s
    "#{sprintf('%.1f', mpg)} lifetime miles per gallon"
  end

  def fill_ups
    count = 1
    fills_hash = {}
    self.fills.order(:created_at).each_with_index do |fill, index|
      fill_hash = {}
      fill_hash[:number_of_fills] = count
      fill_hash[:ppm] = fill.ppm
      fill_hash[:mpg] = fill.mpg
      fills_hash[index] = fill_hash

      fill.fill_to_neck ? count = 1 : count += 1
      
    end
    fills_hash
  end

  # index

  # fill_count
  # filled - bool
  # ppm
  # mpg

  private

  def total_spend
    total = 0
    tank_filled = false
    self.fills.order(created_at: 'DESC').each do |fill|
      if !tank_filled && fill.fill_to_neck
        tank_filled = true
      end

      if tank_filled
        total += fill.total_price
      end
    end
    total
  end

  def total_miles
    total = 0
    tank_filled = false
    self.fills.order(created_at: 'DESC').each do |fill|
      if !tank_filled && fill.fill_to_neck
        tank_filled = true
      end

      if tank_filled
        total += fill.miles_on_trip
      end
    end
    total
  end

  def total_gallons
    total = 0
    tank_filled = false
    self.fills.order(created_at: 'DESC').each do |fill|
      if !tank_filled && fill.fill_to_neck
        tank_filled = true
      end

      if tank_filled
        total += fill.gallons
      end
    end
    total
  end

  def ppm
    total_spend * 100 / total_miles
  end

  def mpg
    total_miles / total_gallons
  end




end

app/models/fill.rb
class Fill < ApplicationRecord
  belongs_to :car

  def ppm_to_s
    if self.fill_to_neck
      "#{sprintf('%.1f', ppm)} pence per mile"
    else
      "Partial fill - price per mile is undetermined"
    end
  end

  def mpg_to_s
    if self.fill_to_neck
      "#{sprintf('%.1f', mpg)} miles per gallon"
    else
      "Partial fill - price per mile is undetermined"
    end
  end

  def gallons
    litres / 4.546
  end


  def litres
    self.total_price * 100 / self.price_per_litre
  end

  def ppm
    total_price * 100 / self.miles_on_trip
  end

  def mpg
    self.miles_on_trip / gallons
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/fills_controller.rb
class FillsController < ApplicationController
  def index
    @cars = Car.all
  end

  def new
    @fill = Fill.new
  end

  def create
    @fill = Fill.new(fill_params)

    if @fill.save
      flash[:notice] = "Saved!"
      redirect_to root_path
    else
      flash[:alert] = "Nope!"
      redirect_to root_path
    end
  end

  def fill_params
    params.require(:fill).permit(:car_id, :price_per_litre, :total_price, :miles_on_trip, :fill_to_neck)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fills_helper.rb
module FillsHelper
end

app/views/fills/index.html.haml
%h1.display-1.mb-4 Fill Ups

= link_to 'Fill Up', new_fill_path, class: "btn btn-lg btn-block btn-primary"

- @cars.each do |car| 
  %h4.display-4= car.title

  %p= car.ppm_to_s
  %p= car.mpg_to_s
  = car.fill_ups

  - car.fills.each do |fill| 
    %p
      %strong= fill.total_price
    %p= fill.ppm_to_s
    %p= fill.mpg_to_s

app/views/fills/new.html.haml
= form_with model: @fill do |f| 
  
  .form-group.mt-5

    = f.label :car_id
    = f.collection_select :car_id, Car.all, :id, :title, {prompt: true}, class: "form-control form-control-lg"

    = f.label :price_per_litre
    = f.number_field :price_per_litre, step: 0.1, class: "form-control form-control-lg"

    = f.label :total_price
    = f.number_field :total_price, step: 0.01, class: "form-control form-control-lg"

    = f.label :miles_on_trip
    = f.number_field :miles_on_trip, step: 0.1, class: "form-control form-control-lg"

    = f.label :tank_filled_completely, for: "fill_fill_to_neck"
    = f.check_box :fill_to_neck, class: "form-control form-control-lg"
      
    = f.submit :add, class: "btn btn-lg btn-block btn-primary mt-4"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Mileage App
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    .container-fluid
      - flash.each do |name, msg| 
        = content_tag :div, msg
      = yield